market/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'market.views.home', name='home'),
    url(r'^learn-more/$', TemplateView.as_view(template_name="learn-more.html")),
    # url(r'^market/', include('market.foo.urls')),

    url(r'^register/$', 'market.views.register', name='register'),
    url(r'^account/login/$', 'market.views.loginview', name='login'),
    url(r'^account/logout/$', 'market.views.logoutview', name='logout'),

    url(r'^app/', include('market.apps.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # dependencies
    (r'^search/', include('haystack.urls')),
)

market/apps/forms.py
from parsley.decorators import parsleyfy
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit
from django import forms

from market.apps.models import App, Review

class AppForm(forms.ModelForm):
    class Meta:
        model = App

@parsleyfy
class SubmitAppForm(forms.Form):
    xml = forms.URLField(
        label = "Install URL",
        required = True,
    )

    def __init__(self, *args, **kwargs):
        super(SubmitAppForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-form-submit-app'
        self.helper.form_class = 'form-submit-app'
        self.helper.form_method = 'post'
        self.helper.form_action = 'apps_submit'

        self.helper.add_input(Submit('submit', 'Submit'))

@parsleyfy
class ReviewForm(forms.Form):
    rating = forms.TypedChoiceField(
        label = "Rating",
        choices = Review.RATING_OPTIONS,
        coerce = lambda x: int(x),
        widget = forms.RadioSelect,
        initial = '3',
        required = True,
    )

    text = forms.CharField(
        label = "Review",
        max_length = 500,
        widget = forms.Textarea,
        required = False,
    )

    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-form-review'
        self.helper.form_class = 'form-review'
        self.helper.form_method = 'post'

        self.helper.layout = Layout(
            Field('rating', css_class="star"),
            Field('text'),
            #ButtonHolder(
            #    Submit('submit', 'Submit')
            #)
        )

        self.helper.add_input(Submit('submit', 'Submit'))

market/apps/templates/apps/app.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block head %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.rating.css' %}"/>
<script src="{% static 'js/jquery.rating.pack.js' %}"></script>
<link rel="zeroinstall" href="{{app.xml}}">
{% endblock head %}

{% block body %}
<div class="container"><div class="body-content">

<h1>{{ app.name }} <small class="text-muted">by {{ app.uploader.username }}</small></h1>
<p><a href="{{ app.homepage }}">{{ app.homepage }}</a></p>

<p>{{ app.description }}</p>

<form method="post" class="form-review" id="id-form-review" action="/app/id/{{ app.id }}/">
<input type="hidden" value="owVCzKZrDXjxobD5cMMIMJqa6UngJaX2" name="csrfmiddlewaretoken">

<div class="control-group" id="div_id_rating">
  <label class="control-label requiredField" for="id_rating_0">Rating<span class="asteriskField">*</span></label>

  <div class="controls">
    <label class="radio"><input type="radio" value="1" id="id_rating_1" name="rating" class="star"></label>
    <label class="radio"><input type="radio" value="2" id="id_rating_2" name="rating" class="star"></label>
    <label class="radio"><input type="radio" value="3" id="id_rating_3" name="rating" checked="checked" class="star"></label>
    <label class="radio"><input type="radio" value="4" id="id_rating_4" name="rating" class="star"></label>
    <label class="radio"><input type="radio" value="5" id="id_rating_5" name="rating" class="star"></label>
  </div>
</div>

<div class="control-group" id="div_id_text">
  <label class="control-label " for="id_text">Review</label>

  <div class="controls">
    <textarea rows="10" name="text" id="id_text" data-maxlength="500" cols="40" class="textarea"></textarea>
  </div>
</div>

<div class="form-actions">
  <input type="submit" id="submit-id-submit" class="btn btn-primary" value="Submit" name="submit">
</div>
</form>

{% if user.is_authenticated %}
<form method="post" class="form-review" id="id-form-review" action="/app/id/3/">
<input type="hidden" value="owVCzKZrDXjxobD5cMMIMJqa6UngJaX2" name="csrfmiddlewaretoken">

<div class="control-group" id="div_id_rating">
<label class="control-label requiredField" for="id_rating_0">Rating<span class="asteriskField">*</span></label>
  <div class="controls">
        <input type="radio" value="1" id="id_rating_1" name="rating" class="star">
        <input type="radio" value="2" id="id_rating_2" name="rating" class="star">
        <input type="radio" value="3" id="id_rating_3" name="rating" checked="checked" class="star">
        <input type="radio" value="4" id="id_rating_4" name="rating" class="star">
        <input type="radio" value="5" id="id_rating_5" name="rating" class="star">
  </div>
</div>

<div class="control-group" id="div_id_text">
<label class="control-label " for="id_text">Review</label>
  <div class="controls">
        <textarea rows="10" name="text" id="id_text" data-maxlength="500" cols="40" class="textarea"></textarea>
  </div>
</div>

<div class="form-actions">
  <input type="submit" id="submit-id-submit" class="btn btn-primary" value="Submit" name="submit">
</div>
</form>
{% endif %}

</div></div>
{% endblock body %}

market/apps/templates/apps/apps_by_category.html
{% extends "home.html" %}

{% block body %}
<div class="container"><div class="body-content">

<h1>Apps in {{ category }}</h1>

{% if applist %}
<div class="list-group">
  {% for app in applist %}
    <a href="{{ app.get_absolute_url }}" class="list-group-item">
      <h4 class="list-group-item-heading">{{ app.name }} <small class="text-muted">by {{ app.uploader.username }}</small></h4>
      <p class="list-group-item-text">{{ app.description }}</p>
    </a>
  {% endfor %}
{% else %}
  <p>There are no apps in this category - yet!</p>
{% endif %}
</div>


</div></div>
{% endblock body %}

market/apps/templates/apps/browse.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block body %}
<div class="container"><div class="body-content">
<h1>Browse Apps</h1>
        <div class="row">
          <div class="col-lg-4 text-center">
            <p><img class="img-thumbnail" src="{% static 'images/network.png' %}"/></p>
            <p><a class="btn btn-default btn-large" href="{% url 'apps_category' 'Network' %}">Network &raquo;</a></p>
          </div>
          <div class="col-lg-4 text-center">
            <p><img class="img-thumbnail" src="{% static 'images/video.png' %}"/></p>
            <p><a class="btn btn-default btn-large" href="{% url 'apps_category' 'AudioVideo' %}">Audio/Video &raquo;</a></p>
          </div>
          <div class="col-lg-4 text-center">
            <p><img class="img-thumbnail" src="{% static 'images/package_graphics.png' %}"/></p>
            <p><a class="btn btn-default btn-large" href="{% url 'apps_category' 'Graphics' %}">Graphics &raquo;</a></p>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-4 text-center">
            <p><img class="img-thumbnail" src="{% static 'images/joystick.png' %}"/></p>
            <p><a class="btn btn-default btn-large" href="{% url 'apps_category' 'Games' %}">Games &raquo;</a></p>
          </div>
          <div class="col-lg-4 text-center">
            <p><img class="img-thumbnail" src="{% static 'images/wordprocessing.png' %}"/></p>
            <p><a class="btn btn-default btn-large" href="{% url 'apps_category' 'Office' %}">Office &raquo;</a></p>
          </div>
          <div class="col-lg-4 text-center">
            <p><img class="img-thumbnail" src="{% static 'images/preferences_other.png' %}"/></p>
            <p><a class="btn btn-default btn-large" href="{% url 'apps_category' 'Settings' %}">Settings &raquo;</a></p>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-4 text-center">
            <p><img class="img-thumbnail" src="{% static 'images/package_education.png' %}"/></p>
            <p><a class="btn btn-default btn-large" href="{% url 'apps_category' 'Education' %}">Education &raquo;</a></p>
          </div>
          <div class="col-lg-4 text-center">
            <p><img class="img-thumbnail" src="{% static 'images/tool.png' %}"/></p>
            <p><a class="btn btn-default btn-large" href="{% url 'apps_category' 'Utilities' %}">Utilities &raquo;</a></p>
          </div>
          <div class="col-lg-4 text-center">
            <p><img class="img-thumbnail" src="{% static 'images/binary.png' %}"/></p>
            <p><a class="btn btn-default btn-large" href="{% url 'apps_category' 'Development' %}">Development &raquo;</a></p>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-4 text-center">
            <p><img class="img-thumbnail" src="{% static 'images/package_science.png' %}"/></p>
            <p><a class="btn btn-default btn-large" href="{% url 'apps_category' 'Science' %}">Science &raquo;</a></p>
          </div>
          <div class="col-lg-4 text-center">
            <p><img class="img-thumbnail" src="{% static 'images/system.png' %}"/></p>
            <p><a class="btn btn-default btn-large" href="{% url 'apps_category' 'System' %}">System &raquo;</a></p>
          </div>
        </div>
</div></div>
{% endblock body %}

market/apps/templates/apps/latest.html
{% extends "home.html" %}

{% block body %}
<div class="container"><div class="body-content">

<h1>Latest Apps</h1>

<div class="list-group">
{% for app in latest_app_list %}
  <a href="{{ app.get_absolute_url }}" class="list-group-item">
    <h4 class="list-group-item-heading">{{ app.name }} <small class="text-muted">by {{ app.uploader.username }}</small></h4>
    <p class="list-group-item-text">{{ app.description }}</p>
  </a>
{% endfor %}
</div>


</div></div>
{% endblock body %}

market/apps/templates/apps/submit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block head %}
{{ block.super }}
<script src="{% static 'js/parsley.min.js' %}"></script>
{% endblock head %}

{% block body %}
<div class="container"><div class="body-content">
<h1>Submit App</h1>

{% if message %}
<div class="alert alert-success">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>{{ message }}</strong>
</div>
{% endif %}

{% crispy form form.helper %}

</div></div>
{% endblock body %}